name: Deploy to GCP VM

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:                                          
      - name: Checkout code #checkout repository    
        uses: actions/checkout@v2

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' 

    - name: Maven Clean Install
      run: mvn clean install

    - name: Copy code to GCP VM 
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          source: "."  
          target: "/var/www/html/java"    # Target directory on GCP VM
             

        



          
            

        
